cytron_controller_node:
  ros__parameters:
    rc1_pin: 12
    rc2_pin: 13
    wheel_base: 0.28
    wheel_radius: 0.050
    max_linear_speed: 0.15
    max_angular_speed: 0.80
    min_speed: 25
    max_speed: 100
    publish_rate: 50.0
    left_trim: 1.0
    right_trim: 1.0
    trim: 0.0
    publish_tf: false
    base_frame: "base_footprint"
    odom_frame: "odom"

cytron_controller:
  ros__parameters:
    rc1_pin: 12
    rc2_pin: 13
    wheel_base: 0.28
    wheel_radius: 0.050
    max_linear_speed: 0.15
    max_angular_speed: 0.80
    min_speed: 25
    max_speed: 100
    publish_rate: 50.0
    left_trim: 1.0
    right_trim: 1.0
    trim: 0.0
    publish_tf: false
    base_frame: "base_footprint"
    odom_frame: "odom"

diff_drive_controller:
  ros__parameters:
    wheel_base: 0.28
    wheel_radius: 0.050
    publish_tf: false
    base_frame: "base_footprint"
    odom_frame: "odom"
